export const worksData = [
  {
    title: "Multi-Role E-Commerce Platform",
    description:
      "A scalable E-commerce web platform developed using MongoDB, Express.js, React.js, and Node.js, designed to support multiple user roles with secure authentication, seamless product discovery, and integrated order management. The system includes role-based dashboards for users, merchants (admins), delivery personnel, and super admins, enabling complete control over shopping, selling, logistics, and platform management. Integrated with Razorpay for payments, OTP-based authentication, invoice generation, and advanced admin analytics, this platform provides a production-ready solution for real-world e-commerce needs.",
    image: "./works/userside.png",
    githubLink: "https://trimahhttps://trimahtech.com/",
    liveLink: "https://trimahtech.com/",
    detailsLink: "https://trimahtech.com/",
    tags: ["React", "UI/UX", "MERN"],
    techStack: ["React", "Node.js", "MongoDB", "...."],
    projectDate: "April 2025 - completed",
  },

  {
    title: "Merchant Panel",
    description:
      "Each merchant has a dedicated dashboard to manage their own products, orders, and analytics. They can add/edit/delete products, manage stock, respond to returns, and view customer details. The dashboard offers real-time sales data, performance graphs, and sorting options for optimal product management. Merchants act independently, similar to vendors in marketplaces like Amazon or Flipkart, and operate under the super admin's oversight.",
    image: "./works/merchantside.png",
    githubLink: "https://github.com/jishnu",
    liveLink: "https://mcmerrys.com/",
    detailsLink: "https://mcmerrys.com",
    tags: ["Event", "Booking", "UI/UX", "MERN"],
    techStack: [
      "React",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Multer",
      "Cloudinary",
      "Razorpay",
      "JWT Auth",
    ],
    projectDate: "June 2025 - completed",
  },
  {
    title: "Super Admin Panel",
    description:
      "The super admin oversees the entire platform with capabilities to create/manage merchant admins and delivery personnel, and control products, categories, users, sliders, and global coupon settings. Super admins can view all order histories, filter by date, and download invoices, and have access to comprehensive analytics including revenue, conversion rates, user activity, and product performance. This role ensures system integrity, business insights, and full control over all roles.",

    image: "./works/superadminside.png",
    githubLink: "https://github.com/JishnuTP?tab=repositories",
    liveLink: "https://www.genailearning.in/user-dashboard",
    detailsLink: "https://github.com/JishnuTP?tab=repositories",
    tags: ["React", "UI/UX", "MERN"],
    techStack: ["React", "Node.js", "MongoDB", "...."],
    projectDate: "Ongoing..",
  },
  {
    title: "Intelligent AI Chatbot with RAG",
    description: "Built a full-stack AI chatbot leveraging Large Language Models (LLMs) via Hugging Face for contextual responses, Retrieval-Augmented Generation (RAG) with Pinecone for semantic search on document queries, and real-time web search through a third-party API for up-to-date information. Developed using Next.js, TypeScript, Node.js, Express, and MongoDB, with features like persistent chat history, message threading, and Google OAuth authentication using NextAuth. Emphasized clean architecture, scalability, and seamless integration of AI with modern web technologies.",
    image: "./works/chatbot.jpg",
    githubLink: "https://github.com/JishnuTP?tab=repositories",
    liveLink: "https://netbay.in/",
    detailsLink: "https://github.com/JishnuTP?tab=repositories",
    tags: ["React", "UI/UX", "Contract"],
    techStack: ["React", "Node.js", "MongoDB", "...."],
    projectDate: "August 2024",
  },
  {
    title: "Delivery Panel",
    description:
      "The delivery panel provides a focused interface for delivery personnel to manage daily orders. After logging in, delivery users can view assigned orders with address, product, and contact details. They can update delivery statuses (e.g., shipped, delivered), and mark cash collected, ensuring proper tracking between merchants and logistics. This role streamlines delivery operations and communicates directly with the admin panel.",
    image: "./works/deliveryportal.png",
    githubLink: "https://github.com/JishnuTP?tab=repositories",
    liveLink: "https://netbay.in/",
    detailsLink: "https://github.com/JishnuTP?tab=repositories",
    tags: ["React", "UI/UX", "Contract"],
    techStack: ["React", "Node.js", "MongoDB", "...."],
    projectDate: "August 2024",
  },

  {
    title: "Invoice Generator",
    description:
      "As part of a larger full-stack business tool, I created a responsive and user-friendly invoice generator using Next.js. The app includes dynamic form handling, real-time calculations, auto-invoice number/date generation, and client-side PDF export functionality. While the UI is optimized using static generation, all invoice logic and interactivity run on the client side for maximum responsiveness. This project reflects my focus on clean code, performance, and scalable design, while showcasing my ability to solve real-world frontend challenges with modern web technologies.",
    image: "./works/invoicegenerator.png",
    githubLink: "https://github.com/design",
    liveLink: "https://github.com/JishnuTP/WorkersOnline.git",
    detailsLink: "https://github.com/JishnuTP/WorkersOnline.git",
    tags: ["UI/UX", "Design", "Web"],
    techStack: ["HTML", "CSS", "JavaScript"],
    projectDate: "August 2023",
  },
  {
    title: "SEO-Optimized Blog App",
    description:
      "This project is my first real-world application using Next.js, where I built a fully functional, SEO-optimized blog platform from scratch. It features server-side rendering (SSR), dynamic routing, and clean UI components designed with Tailwind CSS. I challenged myself to avoid using external tools or libraries to gain a deeper understanding of the framework’s fundamentals. This hands-on approach helped me learn about Next.js architecture, SEO implementation, and performance optimization — making it a key milestone in my transition from the MERN stack to modern React frameworks.",
    image: "./works/blogapp.png",
    githubLink: "https://github.com/JishnuTP/jtpfootwares.git",
    liveLink: "https://github.com/JishnuTP/jtpfootwares.git",
    detailsLink: "https://github.com/JishnuTP/jtpfootwares.git",
    tags: ["Engineering", "Creative", "Innovative"],
    techStack: ["HTML", "Node.js", "NoSQL"],
    projectDate: "May 2023",
  },

  {
    title: "TO-DO",
    description:
      "The ToDo platform is a simple app built with React for the frontend and Firebase for cloud storage. It allows users to create, edit, and delete tasks, and store additional files related to each task. With Firebase Authentication, users can securely sign up and log in. The app syncs tasks in real time across all devices, making it easy to stay organized and manage your tasks from anywhere.",
    image: "./works/todo.png",
    githubLink: "https://github.com/JishnuTP/Todolist.git",
    liveLink: "https://github.com/JishnuTP/Todolist.git",
    detailsLink: "https://github.com/JishnuTP/Todolist.git",
    tags: ["React", "UI", "Firebase", "Mini-project"],
    techStack: ["React", "JavaScript", "Firebase"],
    projectDate: "March 2023",
  },
  {
    title: "Car Cleaning Service Website",
    description:
      "A complete car cleaning service website with multiple pages like Home, About, Services, and Contact. Built with a modern UI, bold visuals, and responsive layout. It delivers a smooth user experience and showcases service details effectively.",
    image: "./works/carcleaning.png",
    githubLink: "https://github.com/JishnuTP/OLX.git",
    liveLink: "https://github.com/JishnuTP/OLX.git",
    detailsLink: "https://github.com/JishnuTP/OLX.git",
    tags: ["Development", "System", "Engineering"],
    techStack: ["React", "JavaScript", "Firebase"],
    projectDate: "March 2023",
  },
  {
    title: "Doctor Appointment website",
    description:
      "A full-featured medical appointment booking system with responsive design. Users can submit personal details, select appointment preferences, and receive organized form validation. Styled with a professional background and glassmorphism UI.",
    image: "./works/doctorappoinment.png",
    githubLink: "https://github.com/JishnuTP/netflix-clone.git",
    liveLink: "https://github.com/JishnuTP/netflix-clone.git",
    detailsLink: "https://github.com/JishnuTP/netflix-clone.git",
    tags: ["Web", "React", "JS"],
    techStack: ["React", "Node.js", "Firebase"],
    projectDate: "June 2023",
  },
];
